Add make for tests #61

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -53,3 +53,65 @@ jobs:
           name: ${{ env.CACHE_NAME }}
           path: ${{ env.CACHE_NAME }}.tar.gz
           retention-days: 1
+
+  run_tests:
+    runs-on: [self-hosted, tests-runner]
+    needs: [checkout]
+    strategy:
+      fail-fast: false
+      matrix:
+        target: [
+            {path:libs/zk/test, target:crypto3_zk_commitment_fold_polynomial_test},
+            {path:libs/zk/test, crypto3_zk_commitment_fri_test},
+            {path:libs/zk/test, crypto3_zk_commitment_lpc_test},
+            {path:libs/zk/test, crypto3_zk_systems_plonk_placeholder_placeholder_test},
+            {path:libs/zk/test, crypto3_zk_commitment_powers_of_tau_test},
+            {path:libs/zk/test, crypto3_zk_commitment_proof_of_knowledge_test},
+            {path:libs/zk/test, crypto3_zk_commitment_r1cs_gg_ppzksnark_mpc_test}
+            #crypto3_zk_math_expression_test
+            #crypto3_zk_systems_plonk_plonk_constraint_test
+
+            # Performance tests pass, but they are excluded from here due to speed.
+            # crypto3_zk_commitment_lpc_performance_test
+
+            # The following tests are temporarily failing.
+            # crypto3_zk_commitment_pedersen_test
+            # crypto3_zk_transcript_kimchi_transcript_test
+            # crypto3_zk_commitment_kimchi_pedersen_test
+            # crypto3_zk_commitment_type_traits_test
+            # crypto3_zk_relations_numeric_qap_test
+            # crypto3_zk_relations_numeric_sap_test
+            # crypto3_zk_relations_numeric_ssp_test
+            # crypto3_zk_routing_algorithms_test_routing_algorithms_test
+            # crypto3_zk_systems_pcd_r1cs_pcd_r1cs_mp_ppzkpcd_r1cs_mp_ppzkpcd_test
+            # crypto3_zk_systems_plonk_pickles_kimchi_test
+            # crypto3_zk_systems_plonk_pickles_oracles_test
+  
+          ]  # Tests to execute
+    steps:
+      - name: Cleanup # TODO - move to scripts on runner
+        run: |
+          rm -rf ./* || true
+          rm -rf ./.??* || true
+
+      - name: Upload checkout job cache
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{ env.CACHE_NAME }}
+
+      - name: Extract artifacts
+        run: |
+          tar -xf ${{ env.CACHE_NAME }}.tar.gz
+          rm ${{ env.CACHE_NAME }}.tar.gz
+
+      - name: Build
+        working-directory: ./build
+        run: cmake --build . -t ${{ matrix.target }}.target
+
+#      - name: Run test
+#        working-directory: ./build
+#        run: |
+#          cd libs/${{ env.LIB_NAME }}/test
+#          COLOR='\033[0;33m'
+#          echo -e "${COLOR}${{ matrix.target }}"
+#          ./${{ matrix.target }}
